"""
npc_tables.py — random NPC generator trait pools (appearance, personality,
ideal, bond, flaw) used by the NPC Generator tab on pages/NPCs.py.

Data-only module (no streamlit), split out so the page file stays readable.
Same root-module pattern as treasure_tables.py / name_tables.py.
"""

# ── NPC Generator tables ──────────────────────────────────────────────────────

NPC_APPEARANCE = [
    "Unusually tall, towers over most crowds",
    "Stocky and broad-shouldered, built like a wall",
    "A long scar running from jaw to ear — deliberately made, not accidental",
    "One missing eye, replaced with a glass one that doesn't quite match",
    "Elaborately braided hair, fresh flowers woven in today",
    "Weathered skin and squinted eyes from years of outdoor work",
    "A distinctive birthmark across the left cheek, shaped like a crescent",
    "Looks impossibly young for the life they've clearly lived",
    "Ancient and deeply wrinkled, moves with surprising quickness",
    "Impeccably dressed in every detail — pressed, polished, perfect",
    "Tattered clothing that was once expensive",
    "Military bearing even in civilian clothes — old habits",
    "Moves with a limp that gets worse when they're tired",
    "Speaks with elaborate hand gestures, can't stop them",
    "Constant nervous fidgeting — rings, buttons, cuffs",
    "Piercing gaze that holds a moment too long",
    "Elaborate tattoos covering neck, hands, and presumably more",
    "Perpetually dirty hands that don't match the rest of their appearance",
    "Calloused hands that have done serious work for years",
    "Dyes their hair an unlikely colour and changes it often",
    "Teeth filed to flat, even points",
    "Never without a specific hat, regardless of the weather",
    "Wearing clothing that was clearly made for someone slightly larger",
    "Eyes that don't quite focus on the same point",
    "Ink stains on the right hand that extend up the wrist",
    "Walks with hands clasped behind the back at all times",
    "Hair worn on one side but shaved close on the other",
    "Rings on every finger, mismatched metals and stones",
    "Scars on both palms, old and faded — the kind made deliberately",
    "Speaks with an accent from a region they've never mentioned visiting",
]

NPC_PERSONALITY = [
    "Boisterous and loud, takes up more space than they need",
    "Quietly observant — speaks once, having already listened twice",
    "Sarcastic at every turn, but always smiling while doing it",
    "Earnestly sincere in a way that makes cynics uncomfortable",
    "Deeply suspicious of strangers; warms up only slowly, if at all",
    "Immediately trusting to the point of naivety",
    "Darkly humorous — jokes about things that probably shouldn't be funny",
    "Overly formal even in casual situations, like they're being watched",
    "Abrupt and blunt, views tact as inefficiency",
    "Long-winded storyteller who always gets to the point eventually",
    "Prone to quoting proverbs, half of which seem to be made up",
    "Relentlessly cheerful in a way that makes you wonder what they're hiding",
    "Melancholy and reflective, clearly carrying something heavy",
    "Easily distracted, brilliant when focused, chaotic otherwise",
    "Intensely focused — gives complete attention or none at all",
    "Speaks in whispers regardless of the setting",
    "Frequently laughs at their own jokes before finishing them",
    "Deadpan and expressionless, rarely gives you a read",
    "Theatrically dramatic about everything, including minor inconveniences",
    "Pragmatic to a fault — reduces everything to costs and outcomes",
    "Changes opinions instantly the moment they sense resistance",
    "Deeply generous with others' time and resources",
    "Refuses to make eye contact — not shyness, calculation",
    "Unfailingly polite in a way that somehow reads as threatening",
    "Asks questions but never waits for the full answer",
    "Every statement trails off, inviting correction or continuation",
    "Loudly self-deprecating in a way that clearly demands reassurance",
    "Compulsively takes notes in a small book; always has one",
    "Always in slightly too much of a hurry to be fully present",
    "Pauses dramatically before speaking, as if every word costs something",
]

NPC_IDEAL = [
    "Power: I will rule this land one day, by whatever means get me there.",
    "Honor: My word is my bond. Everything else can be negotiated.",
    "Freedom: No one should be enslaved or caged — not even by their own obligations.",
    "Knowledge: Truth above all else. Comfortable lies are the most dangerous kind.",
    "Community: We rise together or not at all. I will not step over someone to get ahead.",
    "Greed: Enough is never enough. Someone always has more, and I intend to have it.",
    "Redemption: I have done things I cannot undo. I spend every day trying to earn the right to stop.",
    "Order: Laws exist for good reason. My personal feelings about them are irrelevant.",
    "Chaos: Rules are made by people who benefit from them. I do not benefit.",
    "Love: Family and friendship outweigh any cause. I have been on the other side of that choice.",
    "Survival: Everyone and everything is a resource to be used or avoided. Sentiment is a luxury.",
    "Beauty: Art and elegance can justify almost any means to achieve them.",
    "Legacy: I want to be remembered. Whether for good or ill is a secondary concern.",
    "Loyalty: I owe everything to those who stood by me — and I collect what I'm owed.",
    "Tradition: The old ways exist because they worked. Change for its own sake is reckless.",
    "Ambition: The only thing between me and what I deserve is patience and opportunity.",
    "Justice: Law is a flawed tool. Justice is not — and I will apply it directly.",
    "Faith: The divine will provides. My job is simply to be worth providing for.",
    "Balance: Too much of anything — including good — tips the world toward ruin.",
    "Curiosity: Whatever the cost, there is always more to know than I currently know.",
]

NPC_BOND = [
    "A debt owed to a mentor who saved their life at considerable personal cost.",
    "A sibling who disappeared years ago without explanation — alive or dead, unknown.",
    "An heirloom they would genuinely die before surrendering.",
    "A hometown they swore to return to and protect, and haven't managed either.",
    "A romantic partner waiting for their return, and has been waiting too long.",
    "A rival they cannot stop thinking about, even years after the rivalry ended.",
    "A promise made to a dying friend that is increasingly hard to keep.",
    "Loyalty to a guild or organisation that does not entirely deserve it.",
    "A secret they guard with their entire life — its weight is visible if you know what to look for.",
    "A child they are trying to provide for, who does not know that's what they're doing.",
    "An old war companion buried somewhere they've never been able to find.",
    "A letter they carry but have never opened; the person who sent it is dead.",
    "A debt owed not in coin but in a single unspecified future favour — no questions asked.",
    "A piece of land they were cheated out of, legally and completely, and have never accepted.",
    "A craft or skill they were forbidden from practising, which they practise in secret.",
    "A younger sibling they raised alone, who is now somewhere out in the world without them.",
    "A name they use that isn't their own — the original owner asked them to carry it forward.",
    "An animal companion who trusts them implicitly and probably shouldn't.",
    "A long-running rivalry that has outlasted anyone's memory of what started it.",
    "A specific place — a city, a building, a single room — where everything once made sense.",
]

NPC_FLAW = [
    "Overconfident in their own abilities in ways that have already cost them.",
    "Quick to anger when disrespected, and their threshold for 'disrespect' is low.",
    "Crippling fear of failure — will abandon a plan rather than risk being seen to fail.",
    "Cannot resist a good gamble, and their definition of 'good' is generous.",
    "Deeply envious of those who have more, even when they have enough.",
    "Prone to panic under pressure — freezes or runs rather than thinks.",
    "Tells lies even when the truth would serve better, almost reflexively.",
    "Holds grudges indefinitely and never forgets a slight.",
    "Fundamentally naive about the cruelty the world is capable of.",
    "Uses humour to deflect every serious moment — can't let anything actually land.",
    "Fundamentally incapable of admitting fault, ever, under any circumstances.",
    "Uses generosity as a lever — every gift comes with an unstated future expectation.",
    "Cannot stop talking about one subject that almost no one else cares about.",
    "Flinches from conflict to the point of enabling serious harm through inaction.",
    "Immediately trusts anyone who flatters them, however transparently.",
    "Holds everyone else to a standard they clearly don't apply to themselves.",
    "Cannot let go of sunk costs — throws good resources after bad indefinitely.",
    "Believes they are a fundamentally better person than they actually are.",
    "Desperately needs to be the most competent person in any room they occupy.",
    "Makes promises in earnest that they genuinely cannot keep.",
]
